name: weather_app

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  get: ^4.6.5
  intl: ^0.18.1
  dio: ^4.0.6
  flutter_neumorphic: ^3.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.6+1
  hive: ^2.2.3
  flutter_svg: ^2.0.10+1
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  connectivity_plus: ^6.0.1
  path_provider: ^2.1.2
  flutter_localizations: 
    sdk: flutter 


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/weather_icons/
  
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

scripts:
    hive_box: flutter packages pub run build_runner build --delete-conflicting-outputs
   

